# Open this file in vscode and use it with the rest-client plugin

POST http://51.143.101.249:80/api/v1/service/mlops-aks-service/score HTTP/1.1
Content-Type: application/json
Authorization: Bearer mqOvUc9Lv7euEZztEyu6p16oKbyVGvBz

{
    "data": [{
    "Age": 20,
    "Sex": "male",
    "Job": 0,
    "Housing": "own",
    "Saving accounts": "little",
    "Checking account": "little",
    "Credit amount": 100,
    "Duration": 48,
    "Purpose": "radio/TV"
  }]
}
